### PR TITLE
Added activity scope. Changed dagger implementation. Added subcomponents

### PR DESCRIPTION
**Pull request by ikocijan**
@reisub can you please check out this pull request. I have added submodules and now you can add the module you need to application scope. Since @ActivityScope annotation is added everything that is injected will only live while activity is live.

### CODE REVIEW

**Comment by reisub** [comment]
This looks good. Do we also need to change anything for the robolectric tests to work?

**Comment by ikocijan** [comment]
Good question. We'll need to add "plus" methods to AppTestComponent but that can be done with BaseAppComponent interface.  I think that is all we need. @ikust can you confirm this? I know you added something to this on another project.

**Comment by reisub** [comment]
@ikocijan can you just add the plus methods and use them like we usually do? With a method to inject dependencies in the base activity?

**Comment by ikocijan** [comment]
@reisub Done.

**Comment by reisub** [comment]
Great!

**Pull request merged**
